import json
import logging
from typing import Any, Dict, List, Optional

import pandas as pd
import streamlit as st
from snowflake.snowpark.context import get_active_session
from snowflake.snowpark.session import Session

# =====================================================================
# Configuration & Setup
# =====================================================================
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# =====================================================================
# Core Logic Functions
# =====================================================================

def get_cortex_summary(session: Session, text_content: str) -> Optional[str]:
    """
    Generates a concise summary of the provided text using Snowflake Cortex.

    Args:
        session (Session): The active Snowflake Snowpark session.
        text_content (str): The learning material provided by the user.

    Returns:
        Optional[str]: The generated summary, or None if an error occurs.
    """
    try:
        query = "SELECT SNOWFLAKE.CORTEX.SUMMARIZE(?) AS SUMMARY"
        summary_df: pd.DataFrame = session.sql(query, params=[text_content]).to_pandas()
        return str(summary_df["SUMMARY"].iloc[0])
    except Exception as e:
        logger.error("Failed to generate summary via Cortex: %s", e)
        return None


def get_cortex_flashcards(session: Session, text_content: str) -> Optional[str]:
    """
    Generates interactive flashcards based on the provided text using Snowflake Cortex.

    Args:
        session (Session): The active Snowflake Snowpark session.
        text_content (str): The learning material provided by the user.

    Returns:
        Optional[str]: A JSON string containing the generated flashcards, or None if an error occurs.
    """
    prompt = (
        'Create 5 flashcards as a JSON array of objects with fields '
        '"question" and "answer" for this text: ' + text_content
    )
    try:
        query = "SELECT SNOWFLAKE.CORTEX.COMPLETE('snowflake-arctic', ?) AS FLASHCARDS"
        flash_df: pd.DataFrame = session.sql(query, params=[prompt]).to_pandas()
        return str(flash_df["FLASHCARDS"].iloc[0])
    except Exception as e:
        logger.error("Failed to generate flashcards via Cortex: %s", e)
        return None


def get_cortex_quiz(session: Session, text_content: str) -> Optional[str]:
    """
    Generates a multiple-choice quiz based on the provided text using Snowflake Cortex.

    Args:
        session (Session): The active Snowflake Snowpark session.
        text_content (str): The learning material provided by the user.

    Returns:
        Optional[str]: A JSON string containing the generated quiz, or None if an error occurs.
    """
    prompt = (
        'Create 5 multiple-choice quiz questions as a JSON array of objects '
        'with fields "question", "options" (4 options), and "correct_index" '
        '(0-3) for this text: ' + text_content
    )
    try:
        query = "SELECT SNOWFLAKE.CORTEX.COMPLETE('snowflake-arctic', ?) AS QUIZ"
        quiz_df: pd.DataFrame = session.sql(query, params=[prompt]).to_pandas()
        return str(quiz_df["QUIZ"].iloc[0])
    except Exception as e:
        logger.error("Failed to generate quiz via Cortex: %s", e)
        return None


def evaluate_student_answer(
    session: Session, question: str, expected_answer: str, user_answer: str
) -> Dict[str, Any]:
    """
    Evaluates a student's answer against the expected answer using Snowflake Cortex.

    Args:
        session (Session): The active Snowflake Snowpark session.
        question (str): The flashcard question.
        expected_answer (str): The correct answer generated by the model.
        user_answer (str): The student's submitted answer.

    Returns:
        Dict[str, Any]: A dictionary containing the score, correct points, and missing points.
    """
    eval_prompt = (
        "You are grading a short student answer.\n\n"
        f"Question: {question}\n"
        f"Expected answer: {expected_answer}\n"
        f"Student answer: {user_answer}\n\n"
        "1. Give a score from 0 to 1 (decimals allowed).\n"
        "2. Briefly explain what was correct.\n"
        "3. Briefly explain what was missing or incorrect.\n"
        "Respond strictly as JSON with fields "
        '"score", "correct_points", "missing_points".'
    )
    
    fallback_response: Dict[str, Any] = {
        "score": 0.0,
        "correct_points": "Could not parse detailed feedback.",
        "missing_points": "Error occurred during evaluation."
    }

    try:
        query = "SELECT SNOWFLAKE.CORTEX.COMPLETE('snowflake-arctic', ?) AS EVAL"
        eval_df: pd.DataFrame = session.sql(query, params=[eval_prompt]).to_pandas()
        raw_eval = str(eval_df["EVAL"].iloc[0])
        
        try:
            eval_json = json.loads(raw_eval)
            return {
                "score": float(eval_json.get("score", 0.0)),
                "correct_points": eval_json.get("correct_points", ""),
                "missing_points": eval_json.get("missing_points", "")
            }
        except json.JSONDecodeError as decode_err:
            logger.error("JSON parsing failed for evaluation response: %s", decode_err)
            fallback_response["missing_points"] = raw_eval
            return fallback_response

    except Exception as e:
        logger.error("Failed to evaluate answer via Cortex: %s", e)
        return fallback_response


# =====================================================================
# UI Rendering
# =====================================================================

def render_summary_section() -> None:
    """Renders the auto-generated summary section."""
    if "summary" in st.session_state and st.session_state.summary:
        st.subheader("Auto‑generated summary")
        st.write(st.session_state.summary)


def render_flashcards_section(session: Session) -> None:
    """Renders the interactive flashcards section and handles user evaluation."""
    if "flashcards_json" not in st.session_state or not st.session_state.flashcards_json:
        return

    st.subheader("Interactive flashcards")

    try:
        flashcards = json.loads(st.session_state.flashcards_json)
    except json.JSONDecodeError:
        st.warning("Unable to parse flashcards JSON. Showing raw content.")
        st.json(st.session_state.flashcards_json)
        flashcards = []

    total_flashcards = len(flashcards)
    total_score = 0.0

    for idx, card in enumerate(flashcards):
        question = card.get("question", "")
        correct_answer = card.get("answer", "")

        st.markdown(f"**Card {idx + 1}: {question}**")
        user_answer = st.text_input("Your answer", key=f"fc_{idx}")

        if user_answer:
            with st.spinner("Evaluating your answer..."):
                evaluation = evaluate_student_answer(
                    session=session,
                    question=question,
                    expected_answer=correct_answer,
                    user_answer=user_answer,
                )

            score = evaluation["score"]
            total_score += score

            st.success(f"Score for this card: {score:.2f} / 1.00")
            st.write("What you did well:")
            st.write(f"- {evaluation['correct_points']}")
            st.write("What you missed / got wrong:")
            st.write(f"- {evaluation['missing_points']}")

        st.markdown("---")

    if total_flashcards > 0:
        st.info(
            f"Flashcard score (sum over cards): {total_score:.2f} out of {total_flashcards}. "
            "Each card is graded on a 0–1 scale, then summed."
        )


def render_quiz_section() -> None:
    """Renders the multiple-choice quiz section and handles grading."""
    if "quiz_json" not in st.session_state or not st.session_state.quiz_json:
        return

    st.subheader("Multiple‑choice quiz")

    try:
        quiz = json.loads(st.session_state.quiz_json)
    except json.JSONDecodeError:
        st.warning("Unable to parse quiz JSON. Showing raw content.")
        st.json(st.session_state.quiz_json)
        quiz = []

    user_choices = []

    for idx, question_item in enumerate(quiz):
        question = question_item.get("question", "")
        options = question_item.get("options", [])

        if not options:
            continue

        st.markdown(f"**Q{idx + 1}. {question}**")
        choice = st.radio(
            "Select an option",
            options=list(range(len(options))),
            format_func=lambda i, opts=options: opts[i],
            key=f"q_mc_{idx}",
        )
        user_choices.append(choice)
        st.markdown("---")

    if quiz and st.button("Submit quiz"):
        correct_count = 0
        explanations = []

        for idx, question_item in enumerate(quiz):
            options = question_item.get("options", [])
            correct_idx = question_item.get("correct_index", 0)
            chosen_idx = user_choices[idx]

            if chosen_idx == correct_idx:
                correct_count += 1
                explanations.append(f"Q{idx + 1}: correct option selected → 1 mark awarded.")
            else:
                correct_option = options[correct_idx] if options else ""
                explanations.append(
                    f"Q{idx + 1}: incorrect option selected. "
                    f"Correct answer: '{correct_option}' → 0 marks."
                )

        total_questions = len(quiz)
        if total_questions > 0:
            score_percentage = round((correct_count / total_questions) * 100, 2)
            st.success(f"Quiz score: {score_percentage}% ({correct_count} out of {total_questions} correct).")
            st.write("Scoring breakdown:")
            for explanation in explanations:
                st.write(f"- {explanation}")


def render_main_app() -> None:
    """
    Main application layout and execution flow.
    Initializes the session, renders UI components, and handles user actions.
    """
    # 1. Initialize Snowflake Session
    try:
        session = get_active_session()
    except Exception as e:
        st.error("Failed to connect to Snowflake session. Are you running within Snowflake?")
        logger.error("Snowflake session initialization failed: %s", e)
        return

    st.title("AI Learning Assistant")

    tab_study, tab_insights = st.tabs(["Create Study Pack", "Insights"])

    # ---------------- Tab 1: Create Study Pack ----------------
    with tab_study:
        st.markdown(
            "Paste any learning material (notes, chapter, article) below. "
            "The app uses Snowflake Cortex to generate a concise summary, "
            "interactive flashcards, and a multiple‑choice quiz."
        )

        user_text = st.text_area(
            "Input content",
            height=250,
            placeholder=(
                "Example: Binary search is an efficient algorithm for finding an item "
                "in a sorted array ..."
            ),
        )

        if st.button("Generate study pack", disabled=not user_text.strip()):
            with st.spinner("Generating summary, flashcards, and quiz..."):
                # Caching logic with session_state is fully utilized to avoid
                # re-triggering Snowflake Cortex API calls on every Streamlit interaction.
                summary_text = get_cortex_summary(session, user_text)
                flashcards_text = get_cortex_flashcards(session, user_text)
                quiz_text = get_cortex_quiz(session, user_text)

                if summary_text and flashcards_text and quiz_text:
                    st.session_state.summary = summary_text
                    st.session_state.flashcards_json = flashcards_text
                    st.session_state.quiz_json = quiz_text
                    st.success("Study pack generated successfully.")
                else:
                    st.error("Failed to generate study pack. Please check the logs for more details.")

        # Render dynamically generated content if cached
        render_summary_section()
        render_flashcards_section(session)
        render_quiz_section()

    # ---------------- Tab 2: Insights ----------------
    with tab_insights:
        st.subheader("Insights")
        st.write(
            "This prototype focuses on generating study material from pasted text. "
            "Quiz scores can be stored in Snowflake to build instructor dashboards "
            "for weak‑topic analysis and learner progress."
        )


if __name__ == "__main__":
    render_main_app()
